### ISSUE TITLE
解决了busuanzi访问统计的问题

### ISSUE THREAD

**Issue by Riroaki** [Riroaki/Riroaki.github.io#2]
最近不知道为什么，不蒜子统计出了毛病，在控制台查看元素的时候发现pv和uv的元素都莫名其妙被加上“display: none;”的属性，真是让人莫名火大。

但是一看主题配置和footer.ejs内容都没问题，网上也没有看到相关的说法，真的迷啊。

最后迫不得已，改了css文件，对uv和pv元素进行强制显示：
```css
/* ./themes/matery/source/css/matery.css */
#busuanzi_container_site_pv {
    /* 网站页脚访问pv */
    display: inline !important;
}

#busuanzi_container_site_uv  {
    /* 网站页脚访问uv */
    display: inline !important;
}

#busuanzi_container_page_pv {
    /* 文章访问pv */
    display: inline !important;
}
```
这样终于是搞定了，记录在此。
